name: Tests

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Neovim
      run: sudo snap install nvim --classic

    - name: Install Plenary
      run: |
        git clone https://github.com/nvim-lua/plenary.nvim.git
        mkdir -p $HOME/.local/share/nvim/lazy/
        mv plenary.nvim $HOME/.local/share/nvim/lazy/

    - name: Install Nui
      run: |
        git clone https://github.com/MunifTanjim/nui.nvim
        mkdir -p $HOME/.local/share/nvim/lazy/
        mv nui.nvim $HOME/.local/share/nvim/lazy/

    - name: Install Telescope
      run: |
        git clone https://github.com/nvim-telescope/telescope.nvim
        mkdir -p $HOME/.local/share/nvim/lazy/
        mv telescope.nvim $HOME/.local/share/nvim/lazy/

    - name: Run Tests
      run: make test

    - name: Check for errant util calls
      run: make no-utils

    - name: Run luacheck type check / linter
      run: |
        sudo apt-get install lua-check -y --no-install-recommends
        make check

    - name: Check formatting
      run: |
        sudo apt-get install npm -y --no-install-recommends
        sudo npm install -g @johnnymorganz/stylua-bin
        make check-fmt
